# Generated by Django 5.0.1 on 2024-01-24 22:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUji',
            fields=[
                ('id_datauji', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_datauji',
            },
        ),
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id_kriteria', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kriteria', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_kriteria',
            },
        ),
        migrations.CreateModel(
            name='SubKriteria',
            fields=[
                ('id_sub', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subkriteria', models.CharField(max_length=50)),
                ('bobot', models.FloatField()),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spkcmeans.kriteria')),
            ],
            options={
                'db_table': 'tb_subkriteria',
            },
        ),
        migrations.CreateModel(
            name='DetailDataUji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datauji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spkcmeans.datauji')),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spkcmeans.kriteria')),
                ('subkriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spkcmeans.subkriteria')),
            ],
            options={
                'db_table': 'tb_detaildatauji',
            },
        ),
    ]
